# Common config for all profiles
server:
  port: ${SERVER_PORT:8082}
spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  profiles:
    active: ${PROFILES_ACTIVE:default}
---
spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  config:
    activate:
      on-profile: default
  datasource:
    url: jdbc:postgresql://localhost:5432/lp-sd-db?currentSchema=public
    username: user
    password: user
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
---
spring:
  config:
    activate:
      on-profile: ${PROFILES_ACTIVE}
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    testOnBorrow: true
    validationQuery: SELECT 1
    hikari:
      maximum-pool-size: ${HIKARI_POOL_SIZE:2}
      idleTimeout: 12000
      connectionTimeout: 60000
      leakDetectionThreshold: 60000
    jpa:
      database-platform: org.hibernate.dialect.PostgreSQL9Dialect
      show-sql: false
      properties:
        hibernate:
          temp:
            use_jdbc_metadata_defaults: false

